name: Playwright Tests

on:
  workflow_dispatch: # Trigger manually from GitHub Actions UI

jobs:
  playwright-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Missing Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff2dec1 \
            libvpx7 \
            libevent-2.1-7 \
            libopus0 \
            libgstallocators-1.0-0 \
            libgstapp-1.0-0 \
            libgstpbutils-1.0-0 \
            libgstaudio-1.0-0 \
            libgsttag-1.0-0 \
            libgstvideo-1.0-0 \
            libgstgl-1.0-0 \
            libgstcodecparsers-1.0-0 \
            libgstfft-1.0-0 \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libflite1 \
            libflite-usenglish1 \
            libflite-cmu-grapheme-lang1 \
            libflite-cmu-grapheme-lex1 \
            libflite-cmu-indic-lang1 \
            libflite-cmu-indic-lex1 \
            libflite-cmulex1 \
            libflite-cmu-time-awb1 \
            libflite-cmu-us-awb1 \
            libflite-cmu-us-kal16-1 \
            libflite-cmu-us-kal1 \
            libflite-cmu-us-rms1 \
            libflite-cmu-us-slt1 \
            libgles2-mesa \
            libx264-160  

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: ./gradlew test

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: build/reports/screenshots

      - name: Upload Playwright Trace
        uses: actions/upload-artifact@v4
        with:
          name: playwright-trace
          path: build/reports/trace.zip