name: Playwright Tests

on:
  workflow_dispatch: # Trigger manually from GitHub Actions UI

jobs:
  playwright-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Missing Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff2dec0 \
            libvpx6 \
            libevent-2.1-7 \
            libopus0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libgles2-mesa-dev \
            libx264-dev

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: ./gradlew test

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: build/reports/screenshots

      - name: Upload Playwright Trace
        uses: actions/upload-artifact@v4
        with:
          name: playwright-trace
          path: build/reports/trace.zip